name: Commit Validation

on:
  pull_request:

permissions: read-all

jobs:
  commit_validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}

      # Checkout the repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed to checkout all branches for this Action to work

      # Check the PR diff using the current branch and the base branch of the PR
      - uses: GrantBirki/git-diff-action@v2.0.1
        id: git-diff-action
        with:
          json_diff_file_output: diff.json
          raw_diff_file_output: diff.txt

      # Print the diff in JSON format
      - name: Check commits for validity
        id: validation
        env:
          DIFF: ${{ steps.git-diff-action.outputs.json-diff-path }}
        run: |
          pip install -r requirements.txt
          python validate_commit.py $DIFF

  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number.txt
      - uses: actions/upload-artifact@v4
        with:
          name: pr_number.txt
          path: pr/
