name: 'Close stale PRs'

on:
  workflow_dispatch:

  schedule:
    - cron: '30 1 * * *'

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-pr-label: 'stale'
          stale-pr-message: 'This PR is stale because it has been open for 90 days with no activity. It will be closed in 2 days if there is no further activity.'
          close-pr-message: 'This PR is being closed due to inactivity.'
          days-before-pr-stale: 90
          days-before-pr-close: 2
          days-before-issue-stale: -1
          days-before-issue-close: -1
